# Generated by Django 3.2.18 on 2023-04-21 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_option',
            field=models.ManyToManyField(related_name='no_post_option', to=settings.AUTH_USER_MODEL),
        ),
    ]
