# Generated by Django 3.2.18 on 2023-04-21 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_post_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='select1_content',
        ),
        migrations.AddField(
            model_name='post',
            name='select1_content',
            field=models.ManyToManyField(blank=True, related_name='option1_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='select2_content',
        ),
        migrations.AddField(
            model_name='post',
            name='select2_content',
            field=models.ManyToManyField(blank=True, related_name='option2_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
